name: "Build Helper"
on: workflow_dispatch
env:
    GO_VERSION: '1.21.5'
jobs:
    runbuild:
        name: "Build Linux"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                go-version: ${{env.GO_VERSION}}
                cache-dependency-path: go.sum
            - run: |
                go mod download
                CGO_ENABLED=1 go build -o scripthaus cmd/main.go
            - run: scripthaus
